#!/bin/bash
# Script to gather all NetCDF test outputs into a centralized location
# This script is designed to be reusable by other QA pipelines (compliance-checker, etc.)
#
# Usage: gather_test_outputs.sh <output_directory> [basetemp_directory]
#
# The script:
# 1. Searches for all NetCDF files generated by tests
# 2. Copies them to a centralized directory with preserved structure
# 3. Creates a manifest file listing all gathered files
# 4. Categorizes files by CMIP version (CMIP6 vs CMIP7)
# 5. Skips uncategorized files (e.g. statics) that are not expected to be compliant

set -e

# Default output directory if not specified
OUTPUT_DIR="${1:-tmp/qa_test_outputs}"
BASETEMP_DIR="${2:-}"

echo "=========================================="
echo "Gathering Test Outputs for QA Validation"
echo "=========================================="
echo "Output directory: ${OUTPUT_DIR}"
if [ -n "${BASETEMP_DIR}" ]; then
    echo "Basetemp directory: ${BASETEMP_DIR}"
fi
echo ""

# Create the centralized output directory
mkdir -p "${OUTPUT_DIR}"
mkdir -p "${OUTPUT_DIR}/cmip6"
mkdir -p "${OUTPUT_DIR}/cmip7"

# Initialize counters
total_files=0
cmip6_files=0
cmip7_files=0
skipped_files=0

# Create manifest file
MANIFEST="${OUTPUT_DIR}/manifest.txt"
echo "# Test Output Manifest" > "${MANIFEST}"
echo "# Generated: $(date -u +%Y-%m-%dT%H:%M:%SZ)" >> "${MANIFEST}"
echo "# " >> "${MANIFEST}"

echo "Searching for NetCDF files in test directories..."
echo ""

# Function to categorize and copy files
gather_files() {
    local search_dir=$1
    local label=$2

    if [ ! -d "${search_dir}" ]; then
        echo "Warning: Directory ${search_dir} not found, skipping"
        return
    fi

    echo "Gathering from: ${search_dir} (${label})"

    # Find all .nc files
    while IFS= read -r -d '' ncfile; do
        if [ -f "${ncfile}" ]; then
            # Determine CMIP version from file path or content
            cmip_version=""
            if [[ "${ncfile}" == *"CMIP6"* ]]; then
                cmip_version="cmip6"
                cmip6_files=$((cmip6_files + 1))
            elif [[ "${ncfile}" == *"CMIP7"* ]] || [[ "${ncfile}" == *"CMIP/"* ]]; then
                cmip_version="cmip7"
                cmip7_files=$((cmip7_files + 1))
            else
                # Try to detect from file attributes using ncdump
                if command -v ncdump &> /dev/null; then
                    if ncdump -h "${ncfile}" 2>/dev/null | grep -q 'mip_era = "CMIP7"'; then
                        cmip_version="cmip7"
                        cmip7_files=$((cmip7_files + 1))
                    elif ncdump -h "${ncfile}" 2>/dev/null | grep -q 'mip_era = "CMIP6"'; then
                        cmip_version="cmip6"
                        cmip6_files=$((cmip6_files + 1))
                    fi
                fi
            fi

            # Skip files that couldn't be categorized (e.g. statics files)
            if [ -z "${cmip_version}" ]; then
                skipped_files=$((skipped_files + 1))
                echo "  skipped (uncategorized): ${ncfile}"
                continue
            fi

            # Create unique filename to avoid collisions
            basename=$(basename "${ncfile}")
            # Add a hash of the full path to ensure uniqueness
            path_hash=$(echo "${ncfile}" | md5sum | cut -c1-8)
            unique_name="${path_hash}_${basename}"

            # Copy to categorized directory
            dest_file="${OUTPUT_DIR}/${cmip_version}/${unique_name}"
            cp "${ncfile}" "${dest_file}"

            # Add to manifest
            echo "${ncfile} -> ${cmip_version}/${unique_name}" >> "${MANIFEST}"

            total_files=$((total_files + 1))

            echo "  found: ${ncfile}"
            echo "    -> ${cmip_version}/${unique_name}"
        fi
    done < <(find "${search_dir}" -name "*.nc" -type f -print0 2>/dev/null)
}

# Gather files from different test output directories
gather_files "fremor/tests/test_files/outdir" "CMIP6 basic tests"
gather_files "fremor/tests/test_files/outdir_ppan_only" "Extended test examples"

# Gather files from pytest basetemp directory (CLI and yamler tests)
if [ -n "${BASETEMP_DIR}" ]; then
    gather_files "${BASETEMP_DIR}" "pytest basetemp (CLI + yamler tests)"
fi

# Add summary to manifest
echo "" >> "${MANIFEST}"
echo "# Summary" >> "${MANIFEST}"
echo "# Total files: ${total_files}" >> "${MANIFEST}"
echo "# CMIP6 files: ${cmip6_files}" >> "${MANIFEST}"
echo "# CMIP7 files: ${cmip7_files}" >> "${MANIFEST}"
echo "# Skipped files: ${skipped_files}" >> "${MANIFEST}"

echo ""
echo "=========================================="
echo "Gathering Complete"
echo "=========================================="
echo "Total files gathered: ${total_files}"
echo "  - CMIP6: ${cmip6_files}"
echo "  - CMIP7: ${cmip7_files}"
echo "  - Skipped: ${skipped_files}"
echo ""
echo "Output directory: ${OUTPUT_DIR}"
echo "Manifest file: ${MANIFEST}"

# Exit successfully if we found any files
if [ ${total_files} -gt 0 ]; then
    exit 0
else
    echo "::warning::No NetCDF files were found in test output directories"
    exit 1
fi
