#!/bin/bash
# Script to gather all NetCDF test outputs into a centralized location
# This script is designed to be reusable by other QA pipelines (IOOS compliance-checker, ESGF-QA, etc.)
#
# Usage: gather_test_outputs.sh <output_directory>
#
# The script:
# 1. Searches for all NetCDF files generated by tests
# 2. Copies them to a centralized directory with preserved structure
# 3. Creates a manifest file listing all gathered files
# 4. Categorizes files by CMIP version (CMIP6 vs CMIP7)

set -e

# Default output directory if not specified
OUTPUT_DIR="${1:-/tmp/qa_test_outputs}"

echo "=========================================="
echo "Gathering Test Outputs for QA Validation"
echo "=========================================="
echo "Output directory: ${OUTPUT_DIR}"
echo ""

# Create the centralized output directory
mkdir -p "${OUTPUT_DIR}"
mkdir -p "${OUTPUT_DIR}/cmip6"
mkdir -p "${OUTPUT_DIR}/cmip7"
mkdir -p "${OUTPUT_DIR}/other"

# Initialize counters
total_files=0
cmip6_files=0
cmip7_files=0
other_files=0

# Create manifest file
MANIFEST="${OUTPUT_DIR}/manifest.txt"
echo "# Test Output Manifest" > "${MANIFEST}"
echo "# Generated: $(date -u +%Y-%m-%dT%H:%M:%SZ)" >> "${MANIFEST}"
echo "# " >> "${MANIFEST}"

# Find all NetCDF files in test output directories
# Primary locations:
# - fremorizer/tests/test_files/outdir (from test_cmor_run_subtool.py)
# - fremorizer/tests/test_files/outdir_ppan_only (from test_cmor_run_subtool_further_examples.py)

echo "Searching for NetCDF files in test directories..."
echo ""

# Function to categorize and copy files
gather_files() {
    local search_dir=$1
    local label=$2

    if [ ! -d "${search_dir}" ]; then
        echo "Warning: Directory ${search_dir} not found, skipping"
        return
    fi

    echo "Gathering from: ${search_dir} (${label})"

    # Find all .nc files
    while IFS= read -r -d '' ncfile; do
        if [ -f "${ncfile}" ]; then
            # Determine CMIP version from file path or content
            cmip_version="other"
            if [[ "${ncfile}" == *"CMIP6"* ]]; then
                cmip_version="cmip6"
                ((cmip6_files++))
            elif [[ "${ncfile}" == *"CMIP7"* ]]; then
                cmip_version="cmip7"
                ((cmip7_files++))
            else
                # Try to detect from file attributes
                if command -v ncdump &> /dev/null; then
                    if ncdump -h "${ncfile}" 2>/dev/null | grep -q 'mip_era = "CMIP7"'; then
                        cmip_version="cmip7"
                        ((cmip7_files++))
                    elif ncdump -h "${ncfile}" 2>/dev/null | grep -q 'mip_era = "CMIP6"'; then
                        cmip_version="cmip6"
                        ((cmip6_files++))
                    else
                        ((other_files++))
                    fi
                else
                    ((other_files++))
                fi
            fi

            # Create unique filename to avoid collisions
            basename=$(basename "${ncfile}")
            # Add a hash of the full path to ensure uniqueness
            path_hash=$(echo "${ncfile}" | md5sum | cut -c1-8)
            unique_name="${path_hash}_${basename}"

            # Copy to categorized directory
            dest_file="${OUTPUT_DIR}/${cmip_version}/${unique_name}"
            cp "${ncfile}" "${dest_file}"

            # Add to manifest
            echo "${ncfile} -> ${cmip_version}/${unique_name}" >> "${MANIFEST}"

            ((total_files++))

            echo "  ✓ ${ncfile}"
            echo "    → ${cmip_version}/${unique_name}"
        fi
    done < <(find "${search_dir}" -name "*.nc" -type f -print0 2>/dev/null)
}

# Gather files from different test output directories
gather_files "fremorizer/tests/test_files/outdir" "CMIP6 basic tests"
gather_files "fremorizer/tests/test_files/outdir_ppan_only" "Extended test examples"

# Add summary to manifest
echo "" >> "${MANIFEST}"
echo "# Summary" >> "${MANIFEST}"
echo "# Total files: ${total_files}" >> "${MANIFEST}"
echo "# CMIP6 files: ${cmip6_files}" >> "${MANIFEST}"
echo "# CMIP7 files: ${cmip7_files}" >> "${MANIFEST}"
echo "# Other files: ${other_files}" >> "${MANIFEST}"

echo ""
echo "=========================================="
echo "Gathering Complete"
echo "=========================================="
echo "Total files gathered: ${total_files}"
echo "  - CMIP6: ${cmip6_files}"
echo "  - CMIP7: ${cmip7_files}"
echo "  - Other: ${other_files}"
echo ""
echo "Output directory: ${OUTPUT_DIR}"
echo "Manifest file: ${MANIFEST}"
echo ""

# Create a summary file for easy reference
SUMMARY="${OUTPUT_DIR}/SUMMARY.md"
cat > "${SUMMARY}" << EOF
# Test Output Summary

**Generated:** $(date -u +%Y-%m-%dT%H:%M:%SZ)

## Statistics

- **Total NetCDF files:** ${total_files}
- **CMIP6 files:** ${cmip6_files} (in \`cmip6/\` directory)
- **CMIP7 files:** ${cmip7_files} (in \`cmip7/\` directory)
- **Other files:** ${other_files} (in \`other/\` directory)

## Directory Structure

\`\`\`
${OUTPUT_DIR}/
├── cmip6/          # CMIP6-specific outputs
├── cmip7/          # CMIP7-specific outputs
├── other/          # Unclassified outputs
├── manifest.txt    # Detailed file mapping
└── SUMMARY.md      # This file
\`\`\`

## Files by Category

### CMIP6 Files (${cmip6_files})
EOF

# List CMIP6 files
if [ ${cmip6_files} -gt 0 ]; then
    find "${OUTPUT_DIR}/cmip6" -name "*.nc" -type f | sort | while read -r f; do
        echo "- \`$(basename "$f")\`" >> "${SUMMARY}"
    done
else
    echo "- None" >> "${SUMMARY}"
fi

cat >> "${SUMMARY}" << EOF

### CMIP7 Files (${cmip7_files})
EOF

# List CMIP7 files
if [ ${cmip7_files} -gt 0 ]; then
    find "${OUTPUT_DIR}/cmip7" -name "*.nc" -type f | sort | while read -r f; do
        echo "- \`$(basename "$f")\`" >> "${SUMMARY}"
    done
else
    echo "- None" >> "${SUMMARY}"
fi

cat >> "${SUMMARY}" << EOF

### Other Files (${other_files})
EOF

# List other files
if [ ${other_files} -gt 0 ]; then
    find "${OUTPUT_DIR}/other" -name "*.nc" -type f | sort | while read -r f; do
        echo "- \`$(basename "$f")\`" >> "${SUMMARY}"
    done
else
    echo "- None" >> "${SUMMARY}"
fi

cat >> "${SUMMARY}" << EOF

## Usage for QA Pipelines

This centralized output directory can be used by various QA tools:

### IOOS Compliance Checker
\`\`\`bash
for ncfile in ${OUTPUT_DIR}/*/*.nc; do
    compliance-checker --test=cf --criteria=normal "\${ncfile}"
done
\`\`\`

### ESGF-QA
\`\`\`bash
for ncfile in ${OUTPUT_DIR}/*/*.nc; do
    esgf-qa --project CMIP6 "\${ncfile}"
done
\`\`\`

### Custom Validation
\`\`\`bash
# Process all files
find ${OUTPUT_DIR} -name "*.nc" -type f -exec your-validator {} \;

# Process only CMIP7 files
find ${OUTPUT_DIR}/cmip7 -name "*.nc" -type f -exec your-validator {} \;
\`\`\`

## See Also

- \`manifest.txt\` - Full mapping of source files to gathered files
- Individual QA pipeline documentation for specific usage instructions
EOF

cat "${SUMMARY}"

# Exit successfully if we found any files
if [ ${total_files} -gt 0 ]; then
    exit 0
else
    echo "::warning::No NetCDF files were found in test output directories"
    exit 1
fi
