package:
  name: fremor
  version: '{{ environ.get("GIT_DESCRIBE_TAG", "develop") }}'

source:
  path: .

build:
  script: "{{ PYTHON }} -m pip install . -vv --no-deps"
  number: 0
  noarch: python

requirements:
  build:
    - python>=3.11
    - pip
    - setuptools
    - wheel
  host:
    - python>=3.11
    - pip
    - setuptools
  run:
    - python>=3.11
    - click>=8.2
    - cmor>=3.14.3
    - netcdf4>=1.7
    - numpy>=2
    - pyyaml

test:
  requires:
    - conda-forge::pytest
  source_files:
    - fremor/
  imports:
    - fremor
    - fremor._version
    - fremor.cli
    - fremor.cmor_config
    - fremor.cmor_constants
    - fremor.cmor_finder
    - fremor.cmor_helpers
    - fremor.cmor_init
    - fremor.cmor_mixer
    - fremor.cmor_yamler
  commands:
    - fremor --help
    - fremor config --help
    - fremor find --help
    - fremor init --help
    - fremor run --help
    - fremor yaml --help
    - pytest --durations=5 --log-level DEBUG fremor/

about:
  home: https://github.com/NOAA-GFDL/fremor
  license: Apache-2.0
  license_file: LICENSE.md
  summary: Model output rewriter (CMORizer) for FRE/FMS based models
  description: |
    Written by Ian Laflotte, Sergey Nikonov, Chris Blanton, and NOAA-GFDL Modeling Systems Division

extra:
  recipe-maintainers: "ilaflott"
