name: build_conda
on:
  pull_request:
    branches:

# cancel running jobs if theres a newer push
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  condabuild:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - name: Checkout Files
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Setup Conda
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-activate-base: true
          miniforge-version: latest
          channels: conda-forge,noaa-gfdl

      - name: Configure Conda
        run: |
          echo "removing main and r channels from defaults"
          conda config --remove channels defaults || true
          conda config --remove channels main || true
          conda config --remove channels r || true

          echo "setting strict channel priority"
          conda config --set channel_priority strict

          echo "setting anaconda_upload to no"
          conda config --set anaconda_upload no

          echo "printing conda config just in case"
          conda config --show

      - name: Conda install conda-build
        run: |
          echo "conda install conda-build"
          conda install conda-forge::conda-build

      - name: Build fremorizer Conda Package
        run: |
          echo "conda building fremorizer package and outputting as a tarball"
          mkdir -p /tmp/fremorizer-tarball
          conda build --package-format tar.bz2 --output-folder /tmp/fremorizer-tarball .

      - name: Upload fremorizer Tarball
        uses: actions/upload-artifact@v4
        with:
          name: fremorizer-tarball
          path: /tmp/fremorizer-tarball/noarch/fremorizer-*.tar.bz2
          if-no-files-found: error
