name: publish_conda
on:
  push:
    branches:
      - main
    tags:
      - '*'

permissions:
  contents: read

jobs:
  condapublish:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - name: Checkout Files
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Setup Conda
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-activate: true
          activate-environment: base
          conda-remove-defaults: true
          miniforge-version: latest
          channels: conda-forge,noaa-gfdl

      - name: Configure Conda
        run: |
          echo "setting strict channel priority"
          conda config --set channel_priority strict

          echo "setting anaconda_upload to yes"
          conda config --set anaconda_upload yes

          echo "printing conda config just in case"
          conda config --show

      - name: Conda install conda-build
        run: |
          echo "conda install conda-build"
          conda install conda-forge::conda-build conda-forge::anaconda-client

      - name: Build fremor Conda Package
        run: |
          echo "conda building fremor package"
          export ANACONDA_API_TOKEN=${{ secrets.ANACONDA_TOKEN }}
          conda build .
