name: publish_conda


jobs:
  condapublish:
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash -l {0}

    steps:
      - name: Checkout Files
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Set up base Miniforge
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-activate: true
          activate-environment: base
          miniforge-version: latest
          conda-remove-defaults: true
          channels: conda-forge,noaa-gfdl

      - name: Conda install conda-build
        run: |
          echo "conda install conda-build"
          conda install conda-forge::conda-build conda-forge::anaconda-client

      - name: Configure Conda
        run: |
          echo "setting strict channel priority"
          conda config --set channel_priority strict

          echo "setting anaconda_upload to yes"
          conda config --set anaconda_upload yes

          echo "printing conda config just in case"
          conda config --show

      - name: Conda Build Check
        run: |
          echo ""
          echo "sanity check, conda build check"
          conda build --check .          

      - name: Build fremor Conda Package
        env:
          ANACONDA_API_TOKEN: ${{ secrets.ANACONDA_TOKEN }}
        run: |
          echo ""
          echo "building conda package for publishing"
          conda build --no-include-recipe --no-test .
